package org.qbicc.runtime.deserialization;

/**
 * The ObjectDeserializer used during program startup to initialize the heap.
 * The implementations of most of this class's methods are compiler-generated by a
 * compiler pass defined in the qbicc-plugin-serialization plugin.
 */
public final class RuntimeObjectDeserializer extends ObjectDeserializer {

    public static void initializeHeap() {
        byte[] pickledHeap = getPickledHeap();
        int numberOfObjects = getNumberOfPickledObjects();
        Deserializer deser = new Deserializer(pickledHeap, numberOfObjects, new RuntimeObjectDeserializer());
        deserializeHeap(deser);
    }

    public static void deserializeHeap(Deserializer deser) {
        // The body of this method is replaced by org.qbicc.plugin.serialization.HeapSerializer
    }

    public static byte[] getPickledHeap() {
        // The body of this method is replaced by org.qbicc.plugin.serialization.HeapSerializer
        return null;
    }

    public static int getNumberOfPickledObjects() {
        // The body of this method is replaced by org.qbicc.plugin.serialization.HeapSerializer
        return 0;
    }

    public String createString(byte[] data, byte coder, boolean longLived, boolean immortal) {
        // The body of this method is replaced by org.qbicc.plugin.serialization.HeapSerializer
        return null;
    }

    public Object allocateClass(int typeId, boolean longLived, boolean immortal) {
        // The body of this method is replaced by org.qbicc.plugin.serialization.HeapSerializer
        return null;
    }

    public Object allocatePrimitiveArray(int typeId, int length, boolean longLived, boolean immortal) {
        // The body of this method is replaced by org.qbicc.plugin.serialization.HeapSerializer
        return null;
    }

    public Object[] allocateReferenceArray(int elementTypeId, int length, boolean longLived, boolean immortal) {
        // The body of this method is replaced by org.qbicc.plugin.serialization.HeapSerializer
        return null;
    }

    public void deserializeInstanceFields(int typeId, Object obj, Deserializer deserializer) {
        // The body of this method is replaced by org.qbicc.plugin.serialization.HeapSerializer
    }

    public void deserializePrimitiveArrayData(int typeId, int length, Object array, Deserializer deserializer) {
        // The body of this method is replaced by org.qbicc.plugin.serialization.HeapSerializer
    }
}
