= qbicc

This is the `README` for qbicc.  There's not much here yet but be sure to read link:Overview.adoc[the overview].

== Building

To build the project, execute `mvn install` in the root.

== Class Library

QBICC cannot run without https://github.com/qbicc/qbicc-class-library[`qbicc-class-library`].

After you have built qbicc, fetch and install the class libraries as follows:

[source,shell]
-----
git clone --recurse-submodules git@github.com:qbicc/qbicc-class-library.git
cd qbicc-class-library
mvn install
-----

== Running

To run the driver, first build the project and then use https://jbang.dev[`jbang`] to run it:

[source,shell]
-----
jbang --quiet org.qbicc:qbicc-main:1.0.0-SNAPSHOT --boot-module-path /path/to/main.jar:~/.m2/repository/org/qbicc/rt/qbicc-rt-java.base/11.0.1-SNAPSHOT/qbicc-rt-java.base-11.0.1-SNAPSHOT.jar:~/.m2/repository/org/qbicc/qbicc-runtime-unwind/1.0.0-SNAPSHOT/qbicc-runtime-unwind-1.0.0-SNAPSHOT.jar:~/.m2/repository/org/qbicc/qbicc-runtime-api/1.0.0-SNAPSHOT/qbicc-runtime-api-1.0.0-SNAPSHOT.jar:~/.m2/repository/org/qbicc/qbicc-runtime-gc-nogc/1.0.0-SNAPSHOT/qbicc-runtime-gc-nogc-1.0.0-SNAPSHOT.jar:~/.m2/repository/org/qbicc/qbicc-runtime-main/1.0.0-SNAPSHOT/qbicc-runtime-main-1.0.0-SNAPSHOT.jar --output-path /tmp/output hello/world/Main
-----

Replace the `java.base` JAR with your locally-built JAR path from <<Class Library>>.

For a step-by-step example, see `examples/helloworld/hello/world/Main.java`

== JBang cache

When plugins are added or removed, the jbang cache may become inconsistent and result in build errors.
If that happens, add the `--fresh` option to the above command line. Eg: `jbang --fresh ...`
Alternatively, clear the entire cache using:
[source,shell]
-----
jbang cache clear
-----
